#! /usr/bin/env python
# -*- coding: utf-8 -*-
from snakemake.utils import min_version
import os
import pandas as pd
import re

min_version("6.4.1")

configfile: "config/config.yaml"

include: "rules/common.smk"
#include: "rules/download_bam.smk"
#include: "rules/make_msk_ubam.smk"
#include: "rules/make_ega_ubam.smk"
include: "rules/make_tcga_ubam.smk"
include: "rules/align_star.smk"
include: "rules/telescope.smk"
include: "rules/stringtie.smk"

tcga_manifest = pd.read_csv(config['samples'],sep = "\t",header = 0)
tcga_manifest.set_index("id", inplace = True, drop = False)
tcga_meta = pd.read_csv(config['sample_names_info'],sep = "\t",header = 0)
tcga_meta.set_index(config['tcga_file_id'], inplace = True, drop = False)
gdc_file = pd.concat([tcga_manifest,tcga_meta],axis = 1)
gdc_file.set_index(config['tcga_sample_id'],inplace = True, drop = False)
tcga_samples = gdc_file[config['tcga_sample_id']].unique().tolist()

localrules: sample_complete
rule sample_complete:
    input:
        "results/align_multi/{sample_id}/Aligned.out.cram",
        rules.telescope.output,
        rules.stringtie.output
    output:
        touch("results/complete/{sample_id}.txt")

localrules: all
rule all:
    input:
        expand("results/complete/{s}.txt", s=list(samples.index))

localrules: msk
rule msk:
    input:
        expand("results/complete/{s}.txt", s=msk_samples)

localrules: tcga
rule tcga:
    input:
        expand("results/complete/{s}.txt", s=tcga_samples)

localrules: ega
rule ega:
    input:
        expand("results/complete/{s}.txt", s=ega_samples)
