---
title: "Processing Count Data"
author: "Phoebe Fei"
date: "2022-08-17"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

```{css style_settings, echo = FALSE}
blockquote { 
    font-size: 14px; 
    font-style: italic;
}
h1{
    font-size: 22px;
}
h2{
    font-size: 20px;
}
h3{
    font-size: 18px;
}
h4{
    font-size: 16px;
}

```

### Libraries

```{r, eval = FALSE}
devtools::install_github("nixonlab/scopetools")
```

```{r, message=FALSE}
library(stringr)
library(dplyr)
library(magrittr)
library(scopetools)
```



## MSKCC

Sample names, organized by PD/SD
```{r}
samplenames <- c(
  #SD
  "SK_MEL_1316A_T"	,"SK_MEL_1313A_T","SK_MEL_1313B_T","SK_MEL_1306A_T","SK_MEL_1306B_T","SK_MEL_1331A_T","SK_MEL_1331B_T",	
  #PD
  "SK_MEL_1299A_T","SK_MEL_1299B_T","SK_MEL_1058B_T",	"SK_MEL_1330A_T","SK_MEL_1330B_T","SK_MEL_1328A_T",
  #PD (and has timepoint post-pd)
  "SK_MEL_1327A_T","SK_MEL_1327B_T")
```

### Genes

#### Functions to read and combine gene counts

```{r}
generate_gene_table <- function(directory, name_order = gsub(paste(directory,"\\/",sep = ""),"",list.dirs(directory))[-1], lane = 3){
  for(i in 1:length(name_order)){
    file_direct <- paste0(directory,name_order[i],"/ReadsPerGene.out.tab")
    test <- read.table(file_direct, header = FALSE, row.names = 1)
    if(exists("bindtable")){
      #take out the summary rows
      sample.lane <- data.frame(test[-c(1:4),lane], row.names = rownames(test)[-c(1:4)])
      bindtable <- cbind(bindtable,sample.lane[rownames(bindtable),])
    } else {
      #take out the summary rows
      bindtable <- data.frame(test[-c(1:4),lane], row.names = rownames(test)[-c(1:4)])
    }
  }
  colnames(bindtable) <- name_order
  return(bindtable)
}

```

```{r}
msk_genedirect <- "/Users/phoebefei/Library/CloudStorage/OneDrive-med.cornell.edu/WCM/Metastatic UM Prj/align_multi/MSKCC/"
mskcc_gene <- generate_gene_table(msk_genedirect, name_order = samplenames, lane = 3)
```

### HERVs

#### Import readcounts and assign sample names

```{r}
#create the directory path to reports.tsv
filedirect <- paste("/Users/phoebefei/Library/CloudStorage/OneDrive-med.cornell.edu/WCM/Metastatic UM Prj/telescope/MSKCC/", samplenames, "/report.tsv", sep = "")
#make sample names as colnames
mskcc_herv <- load_telescope_reports(files = filedirect, colnames = samplenames)
#take out no features 
mskcc_herv <- mskcc_herv[which(rownames(mskcc_herv) != "__no_feature"),]
```

## TCGA

### Primary Mets Data from TCGA, unfiltered

```{r}
load("/Users/phoebefei/Library/CloudStorage/OneDrive-med.cornell.edu/WCM/Metastatic UM Prj/primary_UM/analysis2/04-count_data.Rdata")
TCGA_gene <- data.frame(counts.tx)
TCGA_herv <- counts.herv
```

## Nilsson Data

### Gene

```{r}
nil_genedirect <- "/Users/phoebefei/Library/CloudStorage/OneDrive-med.cornell.edu/WCM/Metastatic UM Prj/align_multi/Nilsson/"
nilsson_gene <- generate_gene_table(nil_genedirect, lane = 3)
```

### HERVs

```{r}
nilsson_names <- gsub(paste("/Users/phoebefei/Library/CloudStorage/OneDrive-med.cornell.edu/WCM/Metastatic UM Prj/telescope/Nilsson/","\\/",sep = ""),"",list.dirs("/Users/phoebefei/Library/CloudStorage/OneDrive-med.cornell.edu/WCM/Metastatic UM Prj/telescope/Nilsson/"))[-1]
hervdirect <- paste("/Users/phoebefei/Library/CloudStorage/OneDrive-med.cornell.edu/WCM/Metastatic UM Prj/telescope/Nilsson/",nilsson_names, "/report.tsv", sep = "")
#make sample names as colnames
nilsson_herv <- load_telescope_reports(files = hervdirect, colnames = nilsson_names)
#take out no features 
nilsson_herv <- nilsson_herv[which(rownames(nilsson_herv) != "__no_feature"),]
```

### Combine and filter data
Combine first before filtering

```{r}
#need to replace the colnames
colnames(TCGA_gene) <- gsub("\\.","-",colnames(TCGA_gene))
all_genes <- cbind(TCGA_gene, mskcc_gene[rownames(TCGA_gene),],nilsson_gene[rownames(TCGA_gene),])
mets_genes <- cbind(mskcc_gene,nilsson_gene[rownames(mskcc_gene),])
all_hervs <- cbind(TCGA_herv,mskcc_herv[rownames(TCGA_herv),],nilsson_herv[rownames(TCGA_herv),])
mets_hervs <-  cbind(mskcc_herv,nilsson_herv[rownames(mskcc_herv),])
all_genes <- na.omit(all_genes)
mets_genes <- na.omit(mets_genes)
all_hervs <- na.omit(all_hervs)
mets_hervs <- na.omit(mets_hervs)
```

```{r}
cutoff.count <- 5
mskcc_gene <- mskcc_gene[rowSums(mskcc_gene) > cutoff.count,]
mskcc_herv <- mskcc_herv[rowSums(mskcc_herv) > cutoff.count,]
TCGA_gene <- TCGA_gene[rowSums(TCGA_gene) > cutoff.count,]
TCGA_herv <- TCGA_herv[rowSums(TCGA_herv) > cutoff.count,]
nilsson_gene <- nilsson_gene[rowSums(nilsson_gene) > cutoff.count,]
nilsson_herv <- nilsson_herv[rowSums(nilsson_herv) > cutoff.count,]
```

Do a filtering of all

```{r}
all_genes <- all_genes[rowSums(all_genes) > cutoff.count,]
all_hervs <- all_hervs[rowSums(all_hervs) > cutoff.count,]
mets_hervs <- mets_hervs[rowSums(mets_hervs) > cutoff.count,]
mets_genes <- mets_genes[rowSums(mets_genes) > cutoff.count,]
```
### Write to RData

```{r, eval = FALSE}
save(mskcc_gene ,mskcc_herv ,TCGA_gene , TCGA_herv ,nilsson_gene ,nilsson_herv, all_genes, all_hervs, mets_hervs, mets_genes, file = "/Users/phoebefei/Library/CloudStorage/OneDrive-med.cornell.edu/WCM/Metastatic UM Prj/Rdatas/count_data.RData")
```