samples: "resources/gtex_v8.RNASEQ.Whole_Blood.sample_object.txt"
star_align_multi:
    genomeDir: "/fsx/databases/snakemake_references.git/databases/indexes/STAR_gdc38_gencode38"
    outFilterMultimapNmax: 200
    winAnchorMultimapNmax: 200
telescope:
    annotation: "/fsx/databases/snakemake_references.git/databases/annotations/retro.hg38.v1.gtf"
genome_fasta: "/fsx/databases/snakemake_references.git/databases/sequences/gdc38.fna"
annotation_gtf: "/fsx/databases/snakemake_references.git/databases/annotations/gencode.v38.annotation.gtf"
