samples: "resources/gdc_manifest_20220913_193952.tsv"
sample_names_info: "resources/test_table.tsv"
GDC_token: "/home/tof4003/gdc_token_092022.txt"
local_tmp: "/athena/nixonlab/scratch/tof4003"
star_align_multi:
    genomeDir: "resources/STAR_gdc38_gencode38"
    outFilterMultimapNmax: 200
    winAnchorMultimapNmax: 200
telescope:
    annotation: "resources/retro.hg38.v1.gtf"
genome_fasta: "resources/GRCh38.d1.vd1.fa"
annotation_gtf: "resources/gencode.v38.annotation.gtf"

ega_credentials: "$HOME/.egaconfig"

